name: Convert and Push AVIF

on:
  push:
    branches:
      - main
    paths:
      - '**.png'
      - '**.jpg'
      - '**.jpeg'
      - '!**.avif'

jobs:
  convert-and-push:
    runs-on: ubuntu-latest
    name: Convert images to AVIF and push to branches
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Setup ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Incremental Conversion to AVIF
        run: |
          mkdir -p output
          for file in $(find . -maxdepth 1 -type f \( -iname \*.png -o -iname \*.jpg -o -iname \*.jpeg \) ! -name '*.avif'); do
            avif="output/${file%.*}.avif"
            if [ ! -f "$avif" ] || [ "$file" -nt "$avif" ]; then
              convert "$file" -define "heic:speed=1" -quality 30 "$avif"
            fi
          done

      - name: Commit and push to main branch output folder
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/
          git commit -m "Add converted AVIF images to main branch output folder" || echo "No changes to commit"
          git push

      - name: Copy Converted AVIF images to output folder
        run: |
          mkdir -p /home/runner/output
          cp -r output/*.avif /home/runner/output

      - name: Checkout output branch
        uses: actions/checkout@v4
        with:
          ref: 'output'


      - name: Copy AVIF images to output branch
        run: |
          ls -a
          cp -r /home/runner/output/*.avif .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.avif
          git commit -m "Add converted AVIF images to output branch" || echo "No changes to commit"
          git push origin output
